version: "3.4"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_db:/data/db

  backend:
    depends_on:
      - "mongo"
    build:
      context: ./api
      dockerfile: Dockerfile

  frontend:
    ports:
      - "4000:80"
    depends_on:
      - "backend"
    build:
      context: app
      dockerfile: Dockerfile

volumes:
  mongo_db:
